packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@biomejs/biome": true
  esbuild: true
  cpu-features: false
  protobufjs: false
  ssh2: false
  sharp: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "esbuild"
  - "sharp"
