export type Difficulty = "beginner" | "intermediate" | "advanced";
export type BodyRegion = "upper" | "lower" | "core";

export type EquipmentSeed = { slug: string; en: string; de: string };
export type MuscleGroupSeed = { slug: string; region: BodyRegion; en: string; de: string };
export type MovementSeed = {
  slug: string;
  en: string;
  de: string;
  difficulty: Difficulty;
  primary: string;
  secondary: string[];
  equipment: string[];
  isUnilateral?: boolean;
};

export const EQUIPMENT: EquipmentSeed[] = [
  { slug: "barbell", en: "Barbell", de: "Langhantel" },
  { slug: "dumbbell", en: "Dumbbell", de: "Kurzhantel" },
  { slug: "machine", en: "Machine", de: "Maschine" },
  { slug: "cable", en: "Cable", de: "Kabelzug" },
  { slug: "smith_machine", en: "Smith Machine", de: "Multipresse" },
  { slug: "kettlebell", en: "Kettlebell", de: "Kettlebell" },
  { slug: "resistance_band", en: "Resistance Band", de: "Widerstandsband" },
  { slug: "bodyweight", en: "Bodyweight", de: "Körpergewicht" },
];

export const MUSCLE_GROUPS: MuscleGroupSeed[] = [
  { slug: "chest", region: "upper", en: "Chest", de: "Brust" },
  { slug: "upper_back", region: "upper", en: "Upper Back", de: "Oberer Rücken" },
  { slug: "lats", region: "upper", en: "Lats", de: "Latissimus" },
  { slug: "shoulders", region: "upper", en: "Shoulders", de: "Schultern" },
  { slug: "biceps", region: "upper", en: "Biceps", de: "Bizeps" },
  { slug: "triceps", region: "upper", en: "Triceps", de: "Trizeps" },
  { slug: "forearms", region: "upper", en: "Forearms", de: "Unterarme" },
  { slug: "abs", region: "core", en: "Abs", de: "Bauchmuskeln" },
  { slug: "obliques", region: "core", en: "Obliques", de: "Seitliche Bauchmuskeln" },
  { slug: "lower_back", region: "core", en: "Lower Back", de: "Unterer Rücken" },
  { slug: "quads", region: "lower", en: "Quads", de: "Quadrizeps" },
  { slug: "hamstrings", region: "lower", en: "Hamstrings", de: "Beinbeuger" },
  { slug: "glutes", region: "lower", en: "Glutes", de: "Gesäßmuskeln" },
  { slug: "calves", region: "lower", en: "Calves", de: "Waden" },
  { slug: "adductors", region: "lower", en: "Adductors", de: "Adduktoren" },
];

export const MOVEMENTS: MovementSeed[] = [
  {
    slug: "bench-press",
    en: "Bench Press",
    de: "Bankdrücken",
    difficulty: "intermediate",
    primary: "chest",
    secondary: ["triceps", "shoulders"],
    equipment: ["barbell", "dumbbell", "machine", "smith_machine"],
  },
  {
    slug: "incline-bench-press",
    en: "Incline Bench Press",
    de: "Schrägbankdrücken",
    difficulty: "intermediate",
    primary: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: ["barbell", "dumbbell", "machine", "smith_machine"],
  },
  {
    slug: "chest-fly",
    en: "Chest Fly",
    de: "Fliegende",
    difficulty: "beginner",
    primary: "chest",
    secondary: ["shoulders"],
    equipment: ["dumbbell", "cable", "machine"],
  },
  {
    slug: "push-up",
    en: "Push-Up",
    de: "Liegestütz",
    difficulty: "beginner",
    primary: "chest",
    secondary: ["triceps", "shoulders", "abs"],
    equipment: ["bodyweight"],
  },
  {
    slug: "dip",
    en: "Dip",
    de: "Dips",
    difficulty: "intermediate",
    primary: "chest",
    secondary: ["triceps", "shoulders"],
    equipment: ["bodyweight", "machine"],
  },
  {
    slug: "pull-up",
    en: "Pull-Up",
    de: "Klimmzug",
    difficulty: "intermediate",
    primary: "lats",
    secondary: ["biceps", "upper_back", "forearms"],
    equipment: ["bodyweight"],
  },
  {
    slug: "lat-pulldown",
    en: "Lat Pulldown",
    de: "Latzug",
    difficulty: "beginner",
    primary: "lats",
    secondary: ["biceps", "upper_back"],
    equipment: ["cable", "machine"],
  },
  {
    slug: "bent-over-row",
    en: "Bent-Over Row",
    de: "Vorgebeugtes Rudern",
    difficulty: "intermediate",
    primary: "upper_back",
    secondary: ["lats", "biceps", "lower_back"],
    equipment: ["barbell", "dumbbell"],
  },
  {
    slug: "seated-row",
    en: "Seated Row",
    de: "Rudern sitzend",
    difficulty: "beginner",
    primary: "upper_back",
    secondary: ["lats", "biceps"],
    equipment: ["cable", "machine"],
  },
  {
    slug: "deadlift",
    en: "Deadlift",
    de: "Kreuzheben",
    difficulty: "advanced",
    primary: "lower_back",
    secondary: ["glutes", "hamstrings", "upper_back", "forearms"],
    equipment: ["barbell"],
  },
  {
    slug: "romanian-deadlift",
    en: "Romanian Deadlift",
    de: "Rumänisches Kreuzheben",
    difficulty: "intermediate",
    primary: "hamstrings",
    secondary: ["glutes", "lower_back"],
    equipment: ["barbell", "dumbbell"],
  },
  {
    slug: "back-extension",
    en: "Back Extension",
    de: "Rückenstrecken",
    difficulty: "beginner",
    primary: "lower_back",
    secondary: ["glutes", "hamstrings"],
    equipment: ["bodyweight", "machine"],
  },
  {
    slug: "shrug",
    en: "Shrug",
    de: "Schulterheben",
    difficulty: "beginner",
    primary: "upper_back",
    secondary: ["forearms"],
    equipment: ["barbell", "dumbbell", "smith_machine"],
  },
  {
    slug: "overhead-press",
    en: "Overhead Press",
    de: "Schulterdrücken",
    difficulty: "intermediate",
    primary: "shoulders",
    secondary: ["triceps"],
    equipment: ["barbell", "dumbbell", "machine", "smith_machine"],
  },
  {
    slug: "lateral-raise",
    en: "Lateral Raise",
    de: "Seitheben",
    difficulty: "beginner",
    primary: "shoulders",
    secondary: [],
    equipment: ["dumbbell", "cable", "machine"],
  },
  {
    slug: "front-raise",
    en: "Front Raise",
    de: "Frontheben",
    difficulty: "beginner",
    primary: "shoulders",
    secondary: [],
    equipment: ["dumbbell", "cable"],
  },
  {
    slug: "reverse-fly",
    en: "Reverse Fly",
    de: "Vorgebeugtes Seitheben",
    difficulty: "beginner",
    primary: "shoulders",
    secondary: ["upper_back"],
    equipment: ["dumbbell", "cable", "machine"],
  },
  {
    slug: "face-pull",
    en: "Face Pull",
    de: "Face Pull",
    difficulty: "beginner",
    primary: "shoulders",
    secondary: ["upper_back"],
    equipment: ["cable", "resistance_band"],
  },
  {
    slug: "biceps-curl",
    en: "Biceps Curl",
    de: "Bizepscurl",
    difficulty: "beginner",
    primary: "biceps",
    secondary: ["forearms"],
    equipment: ["barbell", "dumbbell", "cable", "machine"],
  },
  {
    slug: "hammer-curl",
    en: "Hammer Curl",
    de: "Hammercurl",
    difficulty: "beginner",
    primary: "biceps",
    secondary: ["forearms"],
    equipment: ["dumbbell", "cable"],
  },
  {
    slug: "triceps-extension",
    en: "Triceps Extension",
    de: "Trizepsstrecken",
    difficulty: "beginner",
    primary: "triceps",
    secondary: [],
    equipment: ["dumbbell", "cable", "barbell"],
  },
  {
    slug: "triceps-pushdown",
    en: "Triceps Pushdown",
    de: "Trizepsdrücken am Kabel",
    difficulty: "beginner",
    primary: "triceps",
    secondary: [],
    equipment: ["cable"],
  },
  {
    slug: "squat",
    en: "Squat",
    de: "Kniebeuge",
    difficulty: "intermediate",
    primary: "quads",
    secondary: ["glutes", "hamstrings", "lower_back", "abs"],
    equipment: ["barbell", "smith_machine", "bodyweight"],
  },
  {
    slug: "front-squat",
    en: "Front Squat",
    de: "Frontkniebeuge",
    difficulty: "advanced",
    primary: "quads",
    secondary: ["glutes", "abs"],
    equipment: ["barbell"],
  },
  {
    slug: "goblet-squat",
    en: "Goblet Squat",
    de: "Goblet Squat",
    difficulty: "beginner",
    primary: "quads",
    secondary: ["glutes"],
    equipment: ["dumbbell", "kettlebell"],
  },
  {
    slug: "leg-press",
    en: "Leg Press",
    de: "Beinpresse",
    difficulty: "beginner",
    primary: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: ["machine"],
  },
  {
    slug: "lunge",
    en: "Lunge",
    de: "Ausfallschritt",
    difficulty: "intermediate",
    primary: "quads",
    secondary: ["glutes", "hamstrings"],
    equipment: ["bodyweight", "dumbbell", "barbell"],
    isUnilateral: true,
  },
  {
    slug: "leg-extension",
    en: "Leg Extension",
    de: "Beinstrecken",
    difficulty: "beginner",
    primary: "quads",
    secondary: [],
    equipment: ["machine"],
  },
  {
    slug: "leg-curl",
    en: "Leg Curl",
    de: "Beinbeugen",
    difficulty: "beginner",
    primary: "hamstrings",
    secondary: ["calves"],
    equipment: ["machine"],
  },
  {
    slug: "hip-thrust",
    en: "Hip Thrust",
    de: "Hip Thrust",
    difficulty: "intermediate",
    primary: "glutes",
    secondary: ["hamstrings"],
    equipment: ["barbell", "machine", "bodyweight"],
  },
  {
    slug: "hip-adduction",
    en: "Hip Adduction",
    de: "Adduktion",
    difficulty: "beginner",
    primary: "adductors",
    secondary: [],
    equipment: ["machine", "cable"],
  },
  {
    slug: "calf-raise",
    en: "Calf Raise",
    de: "Wadenheben",
    difficulty: "beginner",
    primary: "calves",
    secondary: [],
    equipment: ["machine", "barbell", "dumbbell", "bodyweight", "smith_machine"],
  },
  {
    slug: "plank",
    en: "Plank",
    de: "Unterarmstütz",
    difficulty: "beginner",
    primary: "abs",
    secondary: ["obliques", "lower_back"],
    equipment: ["bodyweight"],
  },
  {
    slug: "crunch",
    en: "Crunch",
    de: "Crunch",
    difficulty: "beginner",
    primary: "abs",
    secondary: ["obliques"],
    equipment: ["bodyweight", "machine", "cable"],
  },
  {
    slug: "leg-raise",
    en: "Leg Raise",
    de: "Beinheben",
    difficulty: "intermediate",
    primary: "abs",
    secondary: ["obliques"],
    equipment: ["bodyweight"],
  },
  {
    slug: "russian-twist",
    en: "Russian Twist",
    de: "Russian Twist",
    difficulty: "beginner",
    primary: "obliques",
    secondary: ["abs"],
    equipment: ["bodyweight", "kettlebell", "dumbbell"],
  },
  {
    slug: "kettlebell-swing",
    en: "Kettlebell Swing",
    de: "Kettlebell Swing",
    difficulty: "intermediate",
    primary: "glutes",
    secondary: ["hamstrings", "lower_back", "shoulders"],
    equipment: ["kettlebell"],
  },
];
